- name: Install MySQL repo
  apt_repository:
    repo: "deb http://repo.mysql.com/apt/ubuntu xenial mysql-8.0"
    state: present

- name: Install MySQL
  apt:
    pkg:
      - mysql-server
      - libapache2-mod-auth-mysql
      - php5-mysql
    state: present
